### ISSUE TITLE
Question: Only works on groups you manage/admin?

### ISSUE THREAD

**Issue by Skeyelab** [egyptian-geeks/posts#2]
Does this work on any group, or just groups you have created?  Say I am a moderator of a group, but not an Admin, will this work?  

Currently getting this when I try:

`➜  posts git:(master) ✗ env 'cat .env' ./download
I, [2018-01-29T15:16:57.506386 #87064]  INFO -- : Getting application access token...
I, [2018-01-29T15:16:57.960859 #87064]  INFO -- : Requesting first page of posts...
Traceback (most recent call last):
	2: from ./download:38:in '<main>'
	1: from /Users/edahl/.rvm/gems/ruby-2.5.0@posts/gems/koala-3.0.0/lib/koala/api/graph_api_methods.rb:129:in 'get_connection'
/Users/edahl/.rvm/gems/ruby-2.5.0@posts/gems/koala-3.0.0/lib/koala/api.rb:50:in 'graph_call': type: GraphMethodException, code: 100, error_subcode: 33, message: Unsupported get request. Object with ID 'XXXXXXXX' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api, x-fb-trace-id: Es/v6hjSfFI [HTTP 400] (Koala::Facebook::ClientError)`

**Comment by kashwaa** [comment]
If the group is public, any valid access token can be used to get the group feed, for  closed and secret groups، a token with user_managed_group permission must be used.

**Comment by emad-elsaid** [comment]
Oh I didn’t see the logs dump in the email notification, well as the errors says, you need to make sure that group if is correct and group is public, if great group is secret or closed I would suggest to be careful with dumping this data as it will be a privacy violation for these people. 
If it’s a public group then double check the ID number for that group

**Comment by Skeyelab** [comment]
Thanks guys.  I am a moderator of a private group, so that seems to be the issue.  Thanks
